### ISSUE TITLE
Clock reverts back to UTC across reboots

### ISSUE THREAD

**Issue by that-itguy** [mrfixit2001/debian_desktop#11] opened 2019-10-04 23:16 UTC
Added my location with correct time zone to the clock. Clock was also set to correct local time CST. When I reboot the clock reverts back to UTC.

**Comment by mrfixit2001** [comment] 2019-10-15 18:39
I cannot reproduce this issue. Please follow this walkthrough for how to set your timezone:
https://linuxize.com/post/how-to-set-or-change-timezone-on-debian-9/
Closing issue, but please re-open if it continues.

**Closed as completed by mrfixit2001** 2019-10-15 18:39 UTC

**Comment by dominictarr** [comment] 2020-01-29 18:24
I also had this problem. the clock app has a "locations" feature but it turns out this does not set the timezone. trying to figure out how it worked I set the time to my local time and then hit set system time. There is not any way to set the timezone via the UI (I looked in the Control Center) so it seems like using the clock app is the correct way to do it.
